### PR TITLE
Fix throwing error if no main entry is defined

### LINKED ISSUE #22: Throws if module has no entry point
If a module (like `babel-runtime`) has no entry point (no `index.js` nor `main` defined in `package.json`), The `resolvePkg()` functions throws with `Cannot find module 'babel-runtime/'`.

I'm unsure how this could be fixed.

### PR DESCRIPTION
**Pull request by topaxi**
Fixes #22

### CODE REVIEW

**Comment by stefanpenner** [comment]
test failures appear unrelated, will investigate shortly.

**Comment by topaxi** [comment]
Looks like `nvm install` failed on macosx, causing the tests to fail. Maybe restarting the tests might fix it?

**Comment by maherbeg** [comment]
Any updates here?

**Comment by stefanpenner** [comment]
@maherbeg test failures need investigation.

**Comment by shaunc** [comment]
Just hit this upstream: https://github.com/babel/broccoli-babel-transpiler/issues/72

I cloned and ran in node 0.12.4 locally. I think the test failure was a travis glitch -- perhaps just try restarting test?

Would be great to get in -- shrinkwrap is such a pain :)

**Comment by stefanpenner** [comment]
kicking travis

**Comment by topaxi** [comment]
Still failing with `/Users/travis/build.sh: line 45: nvm: command not found` on the macosx builds. I sadly have no experience on travis with macosx at all.

**Comment by stefanpenner** [comment]
feel free to disable those in the travis.yml, and we can merge. I don't really see value is linux + OSX tests for this project. Both should be sufficiently similar.

**Comment by topaxi** [comment]
Alright, I've removed osx from travis.yml. Tests are now passing :)

**Comment by shaunc** [comment]
LGTM ... though I admit a certain partisanship ;)

**Comment by stefanpenner** [comment]
thanks all

```
➜  hash-for-dep git:(master) git tag v1.0.2
➜  hash-for-dep git:(master) git push origin v1.0.2
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:stefanpenner/hash-for-dep.git
 * [new tag]         v1.0.2 -> v1.0.2
➜  hash-for-dep git:(master) npm publish
+ hash-for-dep@1.0.2
```

**Pull request merged**
